"""Degeneracy estimators, validated against texts whose answer is known.

Degeneracy qualifies every other measurement in this project: a looping
trajectory occupies one point in representation space and will look maximally
confined for reasons that have nothing to do with semantics. So the detector has
to be right about obvious cases before it is trusted on real ones.
"""

from __future__ import annotations

import numpy as np
import pytest

from semantic_afterlife.analysis.degeneracy import (
    DegeneracyParams,
    compare_segments,
    compression_ratio,
    compute_degeneracy,
    ngram_repetition_rate,
    tokenize_words,
    type_token_ratio,
    unigram_entropy,
)
from semantic_afterlife.errors import AnalysisError

VARIED = (
    "The lattice spacing sets the ultraviolet cutoff and everything else follows. "
    "When the coupling approaches criticality the correlation length grows without "
    "bound, so discretisation artefacts decouple from the observables we care about. "
    "Gauge configurations must then be generated by an algorithm whose autocorrelation "
    "time does not itself diverge across the sampled ensemble."
)
LOOPED = "goodbye and thank you for the conversation " * 40


class TestPrimitives:
    def test_repetition_separates_looped_from_varied(self) -> None:
        varied = ngram_repetition_rate(tokenize_words(VARIED))
        looped = ngram_repetition_rate(tokenize_words(LOOPED))
        assert looped > 0.9
        assert varied < 0.1
        assert looped > varied

    def test_repetition_is_zero_for_all_distinct_ngrams(self) -> None:
        words = [f"w{i}" for i in range(50)]
        assert ngram_repetition_rate(words, 3) == pytest.approx(0.0)

    def test_repetition_handles_texts_shorter_than_the_ngram(self) -> None:
        assert ngram_repetition_rate(["a"], 3) == 0.0
        assert ngram_repetition_rate([], 3) == 0.0

    def test_type_token_ratio_ordering(self) -> None:
        assert type_token_ratio(tokenize_words(VARIED)) > type_token_ratio(tokenize_words(LOOPED))
        assert type_token_ratio([]) == 0.0

    def test_entropy_is_zero_for_a_single_repeated_word(self) -> None:
        assert unigram_entropy(["same"] * 100) == pytest.approx(0.0)
        assert unigram_entropy(tokenize_words(VARIED)) > 5.0

    def test_entropy_is_maximal_for_all_distinct_words(self) -> None:
        words = [f"w{i}" for i in range(64)]
        assert unigram_entropy(words) == pytest.approx(6.0, abs=1e-9)

    def test_compression_ratio_detects_redundancy(self) -> None:
        assert compression_ratio(LOOPED) < compression_ratio(VARIED)
        assert compression_ratio("") == 1.0

    def test_tokenizer_keeps_digits_and_drops_punctuation(self) -> None:
        """Digits are content: a trajectory that collapses into enumeration is degenerate."""
        assert tokenize_words("Hello, world! 42 times.") == ["hello", "world", "42", "times"]

    def test_enumeration_collapse_is_visible(self) -> None:
        enumerated = " ".join(f"{i}." for i in range(1, 300))
        assert type_token_ratio(tokenize_words(enumerated)) > 0
        assert unigram_entropy(tokenize_words(enumerated)) > 0


class TestComputeDegeneracy:
    def _run(self, texts: list[str], **kwargs):  # type: ignore[no-untyped-def]
        ends = (np.arange(len(texts)) + 1) * 1024
        return compute_degeneracy(
            texts,
            trajectory_id="t",
            token_ends=ends,
            W=2048,
            params=DegeneracyParams(),
            **kwargs,
        )

    def test_looped_trajectory_is_flagged(self) -> None:
        result = self._run([LOOPED] * 20)
        assert result.is_degenerate
        assert result.scalars["looping_fraction"] == pytest.approx(1.0)

    def test_varied_trajectory_is_not_flagged(self) -> None:
        result = self._run([VARIED + f" Iteration {i} differed." for i in range(20)])
        assert not result.is_degenerate
        assert result.scalars["looping_fraction"] < 0.2

    def test_partial_collapse_is_flagged_by_fraction(self) -> None:
        """Half looped is well past the 20% threshold, even though half is clean."""
        texts = [VARIED] * 10 + [LOOPED] * 10
        assert self._run(texts).is_degenerate

    def test_verdict_uses_only_the_post_horizon_segment(self) -> None:
        """Pre-horizon chunks still carry the seed and belong to a different process."""
        # W = 2048, chunks of 1024, so only the first two chunks are pre-horizon.
        texts = [LOOPED, LOOPED] + [VARIED + f" {i}" for i in range(18)]
        result = self._run(texts)
        assert result.scalars["n_chunks_post_horizon"] == 18
        assert not result.is_degenerate

    def test_frozen_embeddings_are_detected(self) -> None:
        """A trajectory can stop moving even while its surface forms vary."""
        texts = [VARIED + f" Iteration {i} differed." for i in range(20)]
        frozen = np.tile(np.array([1.0, 0.0, 0.0]), (20, 1))
        result = self._run(texts, embeddings=frozen)
        assert result.scalars["frozen_fraction"] == pytest.approx(1.0)
        assert result.is_degenerate

    def test_moving_embeddings_are_not_frozen(self) -> None:
        texts = [VARIED + f" Iteration {i} differed." for i in range(20)]
        rng = np.random.default_rng(0)
        result = self._run(texts, embeddings=rng.normal(size=(20, 8)))
        assert result.scalars["frozen_fraction"] == pytest.approx(0.0)
        assert not result.is_degenerate

    def test_falling_entropy_shows_as_a_negative_trend(self) -> None:
        texts = [" ".join(f"w{i}" for i in range(max(4, 200 - 10 * step))) for step in range(20)]
        assert self._run(texts).scalars["entropy_trend_per_turnover"] < 0

    def test_mismatched_lengths_are_rejected(self) -> None:
        with pytest.raises(AnalysisError):
            compute_degeneracy(
                [VARIED],
                trajectory_id="t",
                token_ends=np.array([1024, 2048]),
                W=2048,
                params=DegeneracyParams(),
            )

    def test_empty_input_is_rejected(self) -> None:
        with pytest.raises(AnalysisError):
            compute_degeneracy(
                [], trajectory_id="t", token_ends=np.array([]), W=2048, params=DegeneracyParams()
            )


class TestCompareSegments:
    def test_collapse_after_the_split_shows_as_rising_repetition(self) -> None:
        texts = [VARIED + f" {i}" for i in range(10)] + [LOOPED] * 10
        result = compute_degeneracy(
            texts,
            trajectory_id="t",
            token_ends=(np.arange(20) + 1) * 1024,
            W=2048,
            params=DegeneracyParams(),
        )
        table = compare_segments(result, split_token=11 * 1024).set_index("metric")
        assert table.loc["ngram_repetition", "delta"] > 0.5
        assert table.loc["unigram_entropy_bits", "delta"] < 0

    def test_recovery_after_the_split_shows_as_falling_repetition(self) -> None:
        """The real trajectory escaped a degenerate phase; the sign must be right."""
        texts = [LOOPED] * 10 + [VARIED + f" {i}" for i in range(10)]
        result = compute_degeneracy(
            texts,
            trajectory_id="t",
            token_ends=(np.arange(20) + 1) * 1024,
            W=2048,
            params=DegeneracyParams(),
        )
        table = compare_segments(result, split_token=11 * 1024).set_index("metric")
        assert table.loc["ngram_repetition", "delta"] < -0.5
        assert table.loc["unigram_entropy_bits", "delta"] > 0
